apiVersion: v1
kind: PersistentVolume
metadata:
  name: weewx-conf
  labels:
    app: weewx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.101.152
    path: "/home/weewx/nfs/conf"
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: weewx-archive
  labels:
    app: weewx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.101.152
    path: "/home/weewx/nfs/archive"
  storageClassName: nfs
