apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weewx-conf
  labels:
    app: weewx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weewx-archive
  labels:
    app: weewx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
